set-option -g history-limit 10000
set-option -g history-file ~/.tmux_history

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Colors for status bar
set-option -g status-bg colour236
set-option -g status-fg colour3
set -g pane-active-border-style fg=colour121,bold

# Color options for right side of status bar
set-option -g status-right '#[fg=colour233,bg=colour8] #h #[fg=colour233,bg=colour23] %m/%d #[fg=colour233,bg=colour8] %H:%M:%S '
set -g default-terminal "xterm-256color"

# If you SSH into a host in a tmux window, you'll notice the window
# title of your terminal emulator remains to be user@localhost 
# rather than user@server. To allow the title bar to adapt to 
# whatever host you connect to, set the following: 
set -g set-titles on
set -g set-titles-string "#T"

set -g display-panes-time 4000

bind-key -n C-t display-popup

setw -g mouse on

# mouse scrolling
# set -g mouse on

# Enable vi mode
setw -g mode-keys vi

# Colors for status bar
set-option -g status-bg colour236
set-option -g status-fg colour3


#######




#set-option -g default-command "reattach-to-user-namespace -l zsh"
